### ISSUE TITLE
OplogThread: caught exception during bulk upsert, re-upserting documents serially

### ISSUE THREAD

**Issue by kevin-xk** [mongodb-labs/elastic2-doc-manager#13] opened 2016-09-14 10:17 UTC
Used versions: 
-Elasticsearch 2.3.4
-mongo-connector 2.4.1
-es2-doc-manager 0.2.0

Log from mongo-connector:

2016-09-14 17:23:12,901 [ERROR] mongo_connector.oplog_manager:570 - OplogThread: caught exception during bulk upsert, re-upserting documents serially
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mongo_connector/oplog_manager.py", line 567, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/Library/Python/2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 229, in bulk_upsert
    for ok, resp in responses:
  File "/Library/Python/2.7/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/Library/Python/2.7/site-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)

please help me,thx

**Comment by ShaneHarvey** [comment] 2016-09-14 23:31
I think this is a duplicate of #6 which will be fixed in the next release.

**Closed** 2016-09-16 00:13 UTC
